/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as AnalystIndexRouteImport } from './routes/analyst.index'
import { Route as AnalystThreadIdRouteImport } from './routes/analyst.$threadId'
import { Route as ApiAnalystRouteImport } from './routes/api/analyst'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystIndexRoute = AnalystIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalystRoute,
} as any)
const AnalystThreadIdRoute = AnalystThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AnalystRoute,
} as any)
const ApiAnalystRoute = ApiAnalystRouteImport.update({
  id: '/api/analyst',
  path: '/api/analyst',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteWithChildren
  '/analyst/$threadId': typeof AnalystThreadIdRoute
  '/api/analyst': typeof ApiAnalystRoute
  '/analyst/': typeof AnalystIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyst/$threadId': typeof AnalystThreadIdRoute
  '/api/analyst': typeof ApiAnalystRoute
  '/analyst': typeof AnalystIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRouteWithChildren
  '/analyst/$threadId': typeof AnalystThreadIdRoute
  '/api/analyst': typeof ApiAnalystRoute
  '/analyst/': typeof AnalystIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analyst' | '/analyst/$threadId' | '/api/analyst' | '/analyst/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyst/$threadId' | '/api/analyst' | '/analyst'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/analyst/$threadId'
    | '/api/analyst'
    | '/analyst/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRouteWithChildren
  ApiAnalystRoute: typeof ApiAnalystRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/': {
      id: '/analyst/'
      path: '/'
      fullPath: '/analyst/'
      preLoaderRoute: typeof AnalystIndexRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/analyst/$threadId': {
      id: '/analyst/$threadId'
      path: '/$threadId'
      fullPath: '/analyst/$threadId'
      preLoaderRoute: typeof AnalystThreadIdRouteImport
      parentRoute: typeof AnalystRoute
    }
    '/api/analyst': {
      id: '/api/analyst'
      path: '/api/analyst'
      fullPath: '/api/analyst'
      preLoaderRoute: typeof ApiAnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalystRouteChildren {
  AnalystThreadIdRoute: typeof AnalystThreadIdRoute
  AnalystIndexRoute: typeof AnalystIndexRoute
}

const AnalystRouteChildren: AnalystRouteChildren = {
  AnalystThreadIdRoute: AnalystThreadIdRoute,
  AnalystIndexRoute: AnalystIndexRoute,
}

const AnalystRouteWithChildren =
  AnalystRoute._addFileChildren(AnalystRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRouteWithChildren,
  ApiAnalystRoute: ApiAnalystRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
